imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
   # - { resource: google.yml }
    #- { resource: paypal.yml }
    #- { resource: payum.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            numeric_functions:
                DEGREES: DoctrineExtensions\Query\Mysql\Degrees
                ACOS: DoctrineExtensions\Query\Mysql\Acos
                SIN: DoctrineExtensions\Query\Mysql\Sin
                RADIANS: DoctrineExtensions\Query\Mysql\Radians
                COS: DoctrineExtensions\Query\Mysql\Cos
            datetime_functions:
                YEAR : DoctrineExtensions\Query\Mysql\Year
                MONTH : DoctrineExtensions\Query\Mysql\Month
                DAY: DoctrineExtensions\Query\Mysql\Day
            string_functions:
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                DATE: DoctrineExtensions\Query\Mysql\Date
        mappings:
            gedmo_translatable:
                type:      annotation
                prefix:    Gedmo\Translatable\Entity
                dir:       "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                is_bundle: false
                # el alias es opcional, por defecto se utiliza la clave de este mapeo
                alias:     GedmoTranslatable
            gedmo_translator:
                type:      annotation
                prefix:    Gedmo\Translator\Entity
                dir:       "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                is_bundle: false
                # el alias es opcional, por defecto se utiliza la clave de este mapeo
                alias:     GedmoTranslator
            gedmo_loggable:
                type:      annotation
                prefix:    Gedmo\Loggable\Entity
                dir:       "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                is_bundle: false
                # el alias es opcional, por defecto se utiliza la clave de este mapeo
                alias:     GedmoLoggable
            gedmo_tree:
                type:      annotation
                prefix:    Gedmo\Tree\Entity
                dir:       "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                is_bundle: false
                # el alias es opcional, por defecto se utiliza la clave de este mapeo
                alias:     GedmoTree
            gedmo_timestampable:
                type:      annotation
                prefix:    Gedmo\Timestampable\Entity
                dir:       "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Timestampable"
                is_bundle: false
                # el alias es opcional, por defecto se utiliza la clave de este mapeo
                alias:     GedmoTimestampable
            gedmo_sluggable:
                type:      annotation
                prefix:    Gedmo\Sluggable\Entity
                dir:       "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Sluggable"
                is_bundle: false
                # el alias es opcional, por defecto se utiliza la clave de este mapeo
                alias:     GedmoSluggable
            gedmo_blameable:
                type:      annotation
                prefix:    Gedmo\Blameable\Entity
                dir:       "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Blameable"
                is_bundle: false
                # el alias es opcional, por defecto se utiliza la clave de este mapeo
                alias:     GedmoBlameable

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#fos_twitter:
 #   file: %kernel.root_dir%/../vendor/abraham/twitteroauth/src/TwitterOAuth.php
 #   consumer_key: Cnm6I5akuxNlB2BPkTuJMe2ns
  #  consumer_secret: OlkGD27Gy1J66on3KMf0Im96FXkuC5LrrB2H8ZnYLJUmxpQYyR
  #  callback_url: http://networks.jobs4diving.com/web/app_dev.php/es/twitter_success