frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: es|en

backoffice:
    resource: "@BackofficeBundle/Resources/config/routing.yml"
    prefix:   /admin
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /connect   
    
#facebook_login:
#    pattern: /login/check-facebook

#google_login:
#    pattern: /login/check-google
#payum_capture:
 #   resource: "@PayumBundle/Resources/config/routing/capture.xml"
#payum_notify:
#    resource: "@PayumBundle/Resources/config/routing/notify.xml"

