<?php

namespace HootSuite\BackofficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
    public function fetchAll(){
        $em   = $this->getEntityManager();
        $consulta = $em->createQuery('SELECT c FROM BackofficeBundle:Country c ORDER BY c.name ASC');
        return $consulta->getArrayResult();
    }
}
