<?php

namespace HootSuite\BackofficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CuentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentaRepository extends EntityRepository
{
}
