<?php

namespace HootSuite\BackofficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfilesUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilesUsuarioRepository extends EntityRepository
{
    public function findProfilesRedes($usuario){
        $em   = $this->getEntityManager();
        $consulta = $em->createQuery("
            SELECT p,s FROM BackofficeBundle:ProfilesUsuario p
            LEFT JOIN p.social_network s
            WHERE p.usuario = $usuario");
        return $consulta->getResult();
    }
}
