<?php

namespace HootSuite\BackofficeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;
/**
 * RolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolRepository extends EntityRepository
{
    private function _fetchRoles()
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery("SELECT r FROM EntitiesBundle:Rol r order by r.alias ASC");
        return $consulta;
    }
    public function fetchRoles()
    {
        return $this->_fetchRoles()->getArrayResult();
    }
}
