<?php

namespace HootSuite\BackofficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TabColumnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TabColumnRepository extends EntityRepository
{
    public function findAllColumns($tab_id){
        $em   = $this->getEntityManager();
        $consulta = $em->createQuery("
            SELECT tc,c FROM BackofficeBundle:TabColumn tc
            JOIN tc.column c
            WHERE tc.tab = $tab_id
            ORDER BY tc.position ASC");
        return $consulta->getResult();
    }
}
