<?php

namespace HootSuite\BackofficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TabRepository extends EntityRepository
{
    public function countColumns($tab_id){
        $em   = $this->getEntityManager();
        $sql = " 
            SELECT count(tc.id) as value
            FROM tab_column tc
            WHERE tc.tab_id = $tab_id
        ";

        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute();
        return $stmt->fetchColumn(0);
    }
}
