<?php

namespace HootSuite\BackofficeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
    public function getUserProfile($id){
        $em   = $this->getEntityManager();
        $consulta = $em->createQuery("
            SELECT p,n FROM BackofficeBundle:ProfilesUsuario p
            JOIN p.usuario u
            JOIN p.social_network n
            WHERE u.id = $id AND p.selected=1");
        return $consulta->getArrayResult();
    }
    public function getUserOrganizations($id){
        $em = $this->getEntityManager();
        $qb = new QueryBuilder($em);
        $where = $qb->expr()->orx();
        $where->add($qb->expr()->eq('u.id', $id));
        $fields=array('o.id', 'o.name');
        return $qb->select($fields)
            ->from('BackofficeBundle:Organization','o')
            ->leftJoin('o.createdBy','u')
            ->where($where)
            ->getQuery()->getArrayResult();
    }
}
