<?php

namespace HootSuite\BackofficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WorkspaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkspaceRepository extends EntityRepository
{
    public function findTabsByTabId($id){
//        $em   = $this->getEntityManager();
//        $consulta = $em->createQuery("
//            SELECT t FROM BackofficeBundle:tab t
//            JOIN t.workspace w
//            JOIN w.tabs tbs
//            WHERE t.id = $id");
//        return $consulta->getResult();
    }
}
